#!/bin/bash

sudo ufw allow 1723/tcp
sudo ufw allow 3306/tcp
sudo ufw allow 22/tcp
sudo ufw allow 2222/tcp
sudo ufw allow 80
sudo ufw allow http
sudo ufw allow https
sudo ufw allow 443
sudo ufw reload